### PR TITLE
PR for the Bookstore: connect to API project

### PR DESCRIPTION
**Pull request by jose-Abel**
Hello,
This is the PR for the Bookstore connect to API project where I've done the following:
- Refactor my add book and remove book features to persist the changes in the server.
- Refactor the redux code of my application using middleware from the thunk package to make async requests to the API.
- Add book and remove book works in the same way after the refactor and better because now besides updating the local redux store management also updates the API backend.
Cheers.

### CODE REVIEW

**Review by BrianSammit — CHANGES_REQUESTED** [review]
# CHANGES REQUIRED 🔴 🛑
Hello @jose-Abel, great job you are doing so far in this project. 💯
TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 
- Great job connecting to the API

However, there are a few changes to make to move to the next project 🛠️ . Keep working hard 💪 💻 

## Required Changes ♻️

- [x] When I try to run the app I got this error. 

Capture

Kindly fix this minor issue. 😄 💪 

See my inline comment to know what changes are needed. 👇 👀 

Please make these required changes and send it again for another review 👍 💪
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
# HAPPY CODING!!! 😄 

cat


**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by jose-Abel** [comment]
> # CHANGES REQUIRED  
> Hello @jose-Abel, great job you are doing so far in this project. 100 TO HIGHLIGHT:
> 
> * Your project is professional
> * Your repo is professional
> * Well structured files
> * Great job connecting to the API
> 
> However, there are a few changes to make to move to the next project hammer_and_wrench . Keep working hard muscle computer
> 
> ## Required Changes 
> * [x]  When I try to run the app I got this error.
> 
> Capture
> 
> Kindly fix this minor issue. smile muscle
> 
> See my inline comment to know what changes are needed. point_down eyes
> 
> Please make these required changes and send it again for another review +1 muscle Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> # HAPPY CODING!!! 
> cat
> 
> **Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

Hello @BrianSammit. You review someone's else project, not mine. In my project I don't have the store with the composeWithDevTools function on it, I have it like this:

const store = createStore(
  reducer,
  compose(
    applyMiddleware(thunk),
    window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__(),
  ),
);

export default store;

**Comment by BrianSammit** [comment]
Hello @jose-Abel, I review the correct project. Sorry for sending the wrong image. here is the correct one. 

Capture

**Review by SpaYco — COMMENTED** [review]
Hello 👋,

_This is an additional review as a result of the second opinion request._

I received the same error for this, _however_, since the app didn't work, this review should have been invalid (meaning it wouldn't count as a review),

Please fix the issue and ask for another review, if you don't get it approved by the last review, request a second opinion and we'll make the final review for you!

Keep rocking 🚀!

**Comment by jose-Abel** [comment]
> Hello wave,
> 
> _This is an additional review as a result of the second opinion request._
> 
> I received the same error for this, _however_, since the app didn't work, this review should have been invalid (meaning it wouldn't count as a review),
> 
> Please fix the issue and ask for another review, if you don't get it approved by the last review, request a second opinion and we'll make the final review for you!
> 
> Keep rocking rocket!

 @SpaYco Did you pull the "thunk" branch? because I don't see those errors you guys are pointing at.

**Comment by BrianSammit** [comment]
Hi Jose!!
I finally could fix the issue.
So the problem was you were using an extension on your browser that debugs the redux, I install this [extension](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=es) and the was problem fixed 

Let me know if you were using an extention.

**Review by BrianSammit — APPROVED** [review]
# STATUS: APROVED :green_circle: :clap: 

Hello @jose-Abel, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

well-1

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jose-Abel** [comment]
> Hi Jose!! I finally could fix the issue. So the problem was you were using an extension on your browser that debugs the redux, I install this [extension](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=es) and the was problem fixed
> 
> Let me know if you were using an extention.

Sorry about that @BrianSammit, I apologize for that mistake of not mentioning it on the Readme, that extension for sure helped me debugging the Redux flux so that's why I leave it there. Once again sorry and thanks for helping me figure out what was happening!

**Comment by BrianSammit** [comment]
Hi @jose-Abel 
No worries every day we learn something new 
Best regards!! 😄 💯

**Pull request merged**
